# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-18 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_phrase', models.CharField(max_length=2000)),
                ('russian_phrase', models.CharField(max_length=2000)),
                ('context', models.TextField()),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(blank=True, max_length=1000, verbose_name='Авторы')),
                ('caption', models.CharField(max_length=2000, verbose_name='Название')),
                ('journal', models.CharField(blank=True, max_length=2000, verbose_name='Журнал')),
                ('volume', models.CharField(blank=True, max_length=20, verbose_name='Номер')),
                ('year', models.IntegerField(blank=True, verbose_name='Год')),
                ('pages', models.CharField(blank=True, max_length=20, verbose_name='Страницы')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Имя файла')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='pair',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glossary.Source'),
        ),
        migrations.AddField(
            model_name='pair',
            name='tags',
            field=models.ManyToManyField(to='glossary.Tag'),
        ),
    ]
