# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-18 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='pages',
        ),
        migrations.AlterField(
            model_name='pair',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pair',
            name='context',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pair',
            name='source',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='glossary.Source'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='tags',
            field=models.ManyToManyField(blank=True, to='glossary.Tag'),
        ),
    ]
