# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-18 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0002_auto_20180118_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='glossary.Source'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='glossary.Tag'),
        ),
        migrations.AlterField(
            model_name='source',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год'),
        ),
    ]
